
jodconverter:
  local:
    enabled: true
    officeHome: /opt/libreoffice7.3
spring:
  freemarker:
    template-loader-path: classpath:/web/
    suffix: .ftl
    charset: UTF-8
    cache: true
  web:
    resources:
      static-locations: classpath:/static/
      chain:
        cache: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: Asia/Shanghai

server:
  compression:
    enabled: true
  shutdown: graceful

